project:
  type: website
  output-dir: docs
  render:
    - index.qmd           
    - testimonials2022.qmd
    - data/2023
    - data/2024
    - data/2025
    - data/2026/slides.qmd
    #- data/2026/analysis2026.Rmd
    - testimonials2024.qmd
    - feedback.qmd        
    - 2026.qmd            
    - past.qmd            
    - past_scicom.qmd     
    - registration_faq.qmd
    - scicom.qmd  
    - local.qmd
    - speaker.qmd   
    - updates.qmd  
    - dialin.qmd
    - dialin_participants.qmd
    - chat.qmd
    - restaurants.qmd
    - submission.qmd
    - shorttopic.qmd
    - chairs.qmd
    - stats.qmd
    - chairs_instructions.qmd
    - benefits.qmd
    - orgcom.qmd
    - whyattend.qmd

website:
  title: "EFSPI regulatory statistics workshop"
  navbar:
    background: info
    left:
    - text: "2026 workshop"
      menu:
        - text: "Save the date"  
          href: 2026.html
        - text: "Why should I attend the workshop?"  
          href: whyattend.html
    - text: "FAQs"
      menu:
        - text: "FAQ registration"
          href: registration_faq.html
        - text: "FAQ contributors (Speakers, Panelists, Chairs)"
          href: speaker.html
        # - text: "FAQ submissions of contributions"
        #   href: submission.html
        # - text: "FAQ session chairs"
        #   href: chairs_instructions.html
        - text: "Restaurants in Basel"  
          href: restaurants.html
    - text: "Testimonials"
      menu:
        - text: "Testimonials from 2022 workshop"  
          href: testimonials2022.html
        - text: "Linkedin posts reflecting on 2024 workshop"  
          href: testimonials2024.html
        - text: "Linkedin posts reflecting on 2025 workshop"  
          href: testimonials2025.html
    - text: "Past workshops"
      href: past.html
    - text: "Conference statistics"
      href: stats.html
    - text: "Committees"
      menu:
        - text: "Workshop chairs"
          href: chairs.html
        - text: "Local organizing committee"
          href: local.html
        - text: "Organizing committee"
          href: orgcom.html
        - text: "Scientific committee"
          href: scicom.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source


